name: Snyk CI/CD SAST y SCA

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  snyk-sast:
    name: Snyk Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth "$SNYK_TOKEN"

      - name: SAST Scan
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          set +e
          snyk code test --report --org="$SNYK_ORG" --project-name="Test CI/CD SAST Alex" --include-ignores
          exit_code=$?
          set -e
          if [ "$exit_code" -eq 1 ]; then
            exit 0
          fi

  snyk-sca:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install depedencies
        run: npm install

      - name: Install Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth "$SNYK_TOKEN"

      - name: SCA Scan
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          set +e
          snyk monitor --all-projects --org="$SNYK_ORG" --include-ignores
          exit_code=$?
          set -e
          if [ "$exit_code" -eq 1 ]; then
            exit 0
          fi
